_format_version: "2.1"

services:
  - name: ubukonde
    url: http://api.ubukonde.com
    host: api.ubukonde.com
    routes:
      - name: ubukonde
        paths:
          - /ubukonde

  - name: users-create
    url: http://192.168.1.66:1010/api/user/create
    host: 192.168.1.66
    routes:
      - name: users-create
        paths:
          - /users-create

  - name: users
    url: http://192.168.1.66:1010/api/user
    host: 192.168.1.66
    routes:
      - name: users
        paths:
          - /users

  - name: login
    url: http://192.168.1.66:1010/api/user/login
    host: 192.168.1.66
    routes:
      - name: login
        paths:
          - /login

  - name: entries
    url: https://api.publicapis.org/entries
    host: api.publicapis.org
    routes:
      - name: entries
        paths:
          - /entries

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:3000
        - http://localhost:8888
        - http://localhost:8000
        - http://192.168.1.66:1010
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
